version: "2"
services:
  bot_app:
    container_name: bot_app
    build: .
    ports:
      - "3000:3000"
    links:
      - bot_mongo
  bot_mongo:
    container_name: bot_mongo
    image: mongo
    volumes:
      - ./data:/data/db
    ports:
      - "27017:27017"